jag-ccd-application/src/main/java/ca/bc/gov/open/ccd/controllers/HealthController.java, jag-ccd-application/src/main/resources/application.yml, jag-ccd-application/src/test/java/ca/bc/gov/open/ccd/CodeControllerTests.java, jag-ccd-application/src/test/java/ca/bc/gov/open/ccd/HealthControllerTests.java
- Fix health controller value parsing
=> fix build and clean up

jag-ccd-application/src/main/java/ca/bc/gov/open/ccd/controllers/ProcessController.java
=> Removing sensitive information from logs

ccd-common-models/src/main/resources/jaxbConfigs/bindings.xml, ccd-common-models/src/main/resources/xsdSchemas/getDevUtils.xsd, ccd-common-models/src/main/resources/xsdSchemas/getDocument.xsd, ccd-common-models/src/main/resources/xsdSchemas/getDocumentSecure.xsd, jag-ccd-application/src/main/java/ca/bc/gov/open/ccd/configuration/SoapConfig.java, jag-ccd-application/src/main/java/ca/bc/gov/open/ccd/controllers/FileController.java, jag-ccd-application/src/main/resources/xsdSchemas/getDevUtils.wsdl, jag-ccd-application/src/main/resources/xsdSchemas/getDocument.wsdl, jag-ccd-application/src/main/resources/xsdSchemas/getDocumentSecure.wsdl
- Includes GetDocument, GetDocumentSecure and GetDevUtils
- Updated bindings, SoapConfig and dateTime format
=> Added missing wsdl and xsd

jag-ccd-application/src/main/java/ca/bc/gov/open/ccd/controllers/CourtController.java, jag-ccd-application/src/main/java/ca/bc/gov/open/ccd/controllers/ReportController.java
- [JADE-739](https://justice.gov.bc.ca/jira/browse/JADE-739)
CCD getRorport and getRorportSecure need to return respond code]
=> Add ResponseCode/ResponseMsg To Ropreport/RopreportSecure

AutomatedTests/src/main/java/ca/bc/gov/open/ccd/test/services/TestService.java
=> clean logs

AutomatedTests/src/main/java/ca/bc/gov/open/ccd/test/controllers/TestController.java, AutomatedTests/src/main/java/ca/bc/gov/open/ccd/test/services/TestService.java, AutomatedTests/src/main/resources/CodeValues-soapui-project-template.xml, CodeValues-soapui-project.xml
=> CodeValues

AutomatedTests/src/main/java/ca/bc/gov/open/ccd/test/controllers/TestController.java, AutomatedTests/src/main/java/ca/bc/gov/open/ccd/test/services/TestService.java, AutomatedTests/src/main/resources/CriminalFileContent-soapui-project-template.xml, CriminalFileContent-soapui-project.xml
=> CriminalFileContent

AutomatedTests/src/main/java/ca/bc/gov/open/ccd/test/controllers/TestController.java, AutomatedTests/src/main/java/ca/bc/gov/open/ccd/test/services/TestService.java, AutomatedTests/src/main/resources/GetUserLogin-soapui-project-template.xml, GetUserLogin-soapui-project.xml
=> CCD GetUserLogin

.github/workflows/trivy-analysis.yml
- Changes to trivy scanner for api split
=> Changes to trivy scanner for api split

jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/ReportController.java
=> fix rop report error

AutomatedTests/src/main/java/ca/bc/gov/open/ccd/test/services/TestService.java, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/CodeController.java, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/CourtController.java, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/DocumentController.java, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/FileController.java, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/ReportController.java, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/UserController.java, jag-ccd-application-1.2/src/main/java/ca/bc/gov/open/ccd/controllers/CodeController.java, jag-ccd-application-1.2/src/main/java/ca/bc/gov/open/ccd/controllers/CourtController.java, jag-ccd-application-1.2/src/main/java/ca/bc/gov/open/ccd/controllers/DocumentController.java, jag-ccd-application-1.2/src/main/java/ca/bc/gov/open/ccd/controllers/FileController.java, jag-ccd-application-1.2/src/main/java/ca/bc/gov/open/ccd/controllers/ReportController.java
- {add a request to error log}
=> add request to error log

jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/CodeController.java, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/CourtController.java, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/DevUtilsController.java, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/DocumentController.java, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/FileController.java, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/HealthController.java, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/ProcessController.java, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/ReportController.java, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/UserController.java, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/models/RequestSuccessLog.java, jag-ccd-application-1.2/src/main/java/ca/bc/gov/open/ccd/controllers/CodeController.java, jag-ccd-application-1.2/src/main/java/ca/bc/gov/open/ccd/controllers/CourtController.java, jag-ccd-application-1.2/src/main/java/ca/bc/gov/open/ccd/controllers/DocumentController.java, jag-ccd-application-1.2/src/main/java/ca/bc/gov/open/ccd/controllers/FileController.java, jag-ccd-application-1.2/src/main/java/ca/bc/gov/open/ccd/models/RequestSuccessLog.java
=> add success log to endpoints

.gitignore, AutomatedTests/src/main/java/ca/bc/gov/open/ccd/test/controllers/TestController.java, AutomatedTests/src/main/java/ca/bc/gov/open/ccd/test/services/TestService.java, AutomatedTests/src/main/resources/CCDGetCivilFileContentSecure-soapui-project-template.xml
=> CCDGetCivilFileContentSecure

.gitignore, AutomatedTests/src/main/java/ca/bc/gov/open/ccd/test/controllers/TestController.java, AutomatedTests/src/main/java/ca/bc/gov/open/ccd/test/services/TestService.java, AutomatedTests/src/main/resources/CCDCodeValuesSecure-soapui-project-template.xml, AutomatedTests/src/main/resources/application.yml
=> CCDCodeValueSecure

gitops/openshift/apps/jag-ccd-1-2/template/jag-ccd-1-2.yaml
=> add secure secretes

jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/DocumentController.java, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/ReportController.java, jag-ccd-application-1.2/src/main/java/ca/bc/gov/open/ccd/controllers/DocumentController.java, jag-ccd-application-1.2/src/main/java/ca/bc/gov/open/ccd/controllers/ReportController.java
- {add logging to getdocument getropreport}
=> add logging to getdocument getropreport

ccd-common-models/src/main/resources/xsdSchemas/proccessResults.xsd, jag-ccd-application-1.1/src/test/java/ca/bc/gov/open/ccd/ProcessControllerTests.java
=> date format

gitops/openshift/apps/automationtests-api/template/jag-ccd-tests.env, gitops/openshift/apps/automationtests-api/template/jag-ccd-tests.yaml
=> add httpheaders and remove unnecessary label

gitops/openshift/apps/jag-ccd-1-1/template/jag-ccd-1-1.yaml, gitops/openshift/apps/jag-ccd-1-2/template/jag-ccd-1-2.yaml, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/ReportController.java, jag-ccd-application-1.1/src/main/resources/application.yml, jag-ccd-application-1.2/src/main/java/ca/bc/gov/open/ccd/controllers/ReportController.java, jag-ccd-application-1.2/src/main/resources/application.yml
=> fix rop report param parsing

jag-ccd-application-1.1/src/main/resources/logback.xml, jag-ccd-application-1.2/src/main/resources/logback.xml
=> add date to log

ccd-civil-models/src/main/resources/xsdSchemas/civilFileContent.xsd, jag-ccd-application-1.1/src/test/java/ca/bc/gov/open/ccd/FileControllerTests.java
=> fix enterDtm in civilFileContent

gitops/openshift/apps/jag-ccd-1-1/template/jag-ccd-1-1.yaml, gitops/openshift/apps/jag-ccd-1-2/template/jag-ccd-1-2.env, gitops/openshift/apps/jag-ccd-1-2/template/jag-ccd-1-2.yaml, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/DocumentController.java, jag-ccd-application-1.1/src/main/resources/application.yml, jag-ccd-application-1.2/src/main/java/ca/bc/gov/open/ccd/controllers/DocumentController.java, jag-ccd-application-1.2/src/main/resources/application.yml
=> fix getDocument and secure

jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/UserController.java, jag-ccd-application-1.1/src/test/java/ca/bc/gov/open/ccd/UserControllerTest.java
=> fixed new getparticiantinfo and its unit test

ccd-common-models/src/main/resources/xsdSchemas/proccessResults.xsd, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/ProcessController.java
=> more index

ccd-common-models/src/main/resources/xsdSchemas/proccessResults.xsd, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/ProcessController.java
=> civilorder

ccd-common-models/src/main/resources/xsdSchemas/proccessResults.xsd, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/ProcessController.java
=> added ids for CriminalResultsDetail and NextAppearanceCRType

ccd-common-models/src/main/resources/xsdSchemas/proccessResults.xsd, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/ProcessController.java
=> add civil result

ccd-common-models/src/main/resources/xsdSchemas/proccessResults.xsd, jag-ccd-application-1.1/src/main/java/ca/bc/gov/open/ccd/controllers/ProcessController.java
=> Added identifier for the remaining process endpoints where needed

gitops/openshift/apps/nginx/template/README.md, gitops/openshift/apps/nginx/template/nginx_jag_ccd.env, gitops/openshift/apps/nginx/template/nginx_jag_ccd.yaml
=> decommission wm

jag-ccd-application-1.1/Dockerfile, jag-ccd-application-1.2/Dockerfile, pom.xml
=> base image update

ccd-court-list-models/src/main/resources/xsdSchemas/courtList.xsd, jag-ccd-application/src/main/resources/xsdSchemas/courtList.wsdl
=> update xsd and wsdl

README.md
=> add read.me file

ccd-civil-models/src/main/resources/xsdSchemas/civilFileContent.xsd, ccd-court-list-models/src/main/resources/xsdSchemas/courtList.xsd, jag-ccd-application/src/main/resources/xsdSchemas/civilFileContent.wsdl, jag-ccd-application/src/main/resources/xsdSchemas/courtList.wsdl
=> CCD-1271 added language code

ccd-common-models/src/main/resources/xsdSchemas/proccessResults.xsd, jag-ccd-application/src/main/resources/xsdSchemas/processResults.wsdl
=> update processResult wdsl

README.md, jag-ccd-application/src/main/java/ca/bc/gov/open/ccd/configuration/SoapConfig.java, jag-ccd-application/src/main/resources/application-test.yml, jag-ccd-application/src/main/resources/application.yml
=> add read timeout to resttemplate to avoid ords connection timeout

ccd-common-models/src/main/resources/xsdSchemas/proccessResults.xsd, ccd-court-list-models/src/main/resources/xsdSchemas/courtList.xsd, jag-ccd-application/src/main/resources/xsdSchemas/courtList.wsdl, jag-ccd-application/src/main/resources/xsdSchemas/processResults.wsdl
=> data model changes

jag-ccd-application/src/main/java/ca/bc/gov/open/ccd/controllers/DocumentController.java
=> add logs on getDocument

jag-ccd-application/Dockerfile, jag-ccd-application/src/main/java/ca/bc/gov/open/ccd/controllers/DocumentController.java
=> remove heap size in docker file

.github/workflows/automationtestapi.yml, .github/workflows/main.yml
=> did not change 11 to 17 in a couple of github workflows

AutomatedTests/pom.xml
=> fix automation vulnerabilities

AutomatedTests/pom.xml
=> fix the automation test severe warning

ccd-common-models/src/main/resources/xsdSchemas/getDocument.xsd, jag-ccd-application/src/main/java/ca/bc/gov/open/ccd/controllers/DocumentController.java, jag-ccd-application/src/main/resources/xsdSchemas/getDocument.wsdl
Added flag to indicate getting the translated document rather than the original in getDocument
=> CCD-1275 - get translated doc

ccd-common-models/src/main/resources/xsdSchemas/proccessResults.xsd, jag-ccd-application/pom.xml, jag-ccd-application/src/main/resources/xsdSchemas/processResults.wsdl, jag-ccd-application/src/test/java/ca/bc/gov/open/ccd/ProcessControllerTests.java, pom.xml
=> modify BanInfoType in wsdl

.github/workflows/trivy-analysis.yml, jag-ccd-application/pom.xml
=> fix vulnerabilities and trivy scan workflow

ccd-common-models/src/main/resources/xsdSchemas/proccessResults.xsd, ccd-court-list-models/src/main/resources/xsdSchemas/courtList.xsd, jag-ccd-application/src/main/resources/xsdSchemas/courtList.wsdl, jag-ccd-application/src/main/resources/xsdSchemas/processResults.wsdl
=> remove AccusedNotRequiredYN because it is in future release, Oct release

ccd-civil-models/src/main/resources/xsdSchemas/civilFileContent.xsd, ccd-court-list-models/src/main/resources/xsdSchemas/courtList.xsd, jag-ccd-application/src/main/resources/xsdSchemas/civilFileContent.wsdl, jag-ccd-application/src/main/resources/xsdSchemas/courtList.wsdl
=> add IndigenousLawFileYn to wsdl

ccd-court-list-models/src/main/resources/xsdSchemas/courtList.xsd, jag-ccd-application/src/main/resources/xsdSchemas/courtList.wsdl
=> remove IndigenousLawFileYn from courtlist

ccd-code-coverage/pom.xml, jag-ccd-application/pom.xml, pom.xml
=> fix vulnerabilities

ccd-common-models/src/main/resources/xsdSchemas/proccessResults.xsd, ccd-court-list-models/src/main/resources/xsdSchemas/courtList.xsd, jag-ccd-application/src/main/resources/xsdSchemas/courtList.wsdl, jag-ccd-application/src/main/resources/xsdSchemas/processResults.wsdl
=> uncomment the changes made on May 9, 2023 for the JUSTINCSB-2289 changes

.github/workflows/dev-jag-ccd-build-push.yml, .github/workflows/dev-jag-ccd-tests-build-push.yml, .github/workflows/promote-prod.yml, .github/workflows/promote-test.yml
=> Initial build - new workflows

.github/workflows/dev-jag-ccd-build-push.yml, .github/workflows/dev-jag-ccd-tests-build-push.yml, .github/workflows/promote-prod.yml, .github/workflows/promote-test.yml
=> Modified ci/cd pipelines

AutomatedTests/pom.xml, ccd-civil-models/pom.xml, ccd-common-models/pom.xml, ccd-court-list-models/pom.xml, jag-ccd-application/pom.xml, pom.xml
=> update to spring boot 3.3.6

AutomatedTests/pom.xml, ccd-civil-models/pom.xml, ccd-common-models/pom.xml, ccd-court-list-models/pom.xml, jag-ccd-application/pom.xml, pom.xml
=> Revert "update to spring boot 3.3.6"

AutomatedTests/pom.xml, pom.xml
=> update spring boot to 3.3.7

.github/workflows/automationtestapi.yml_old, .github/workflows/codeclimate.yml, .github/workflows/dev-jag-ccd-build-push.yml, .github/workflows/dev-jag-ccd-tests-build-push.yml, .github/workflows/main.yml, .github/workflows/openshift-imagetagging.yml_old, .github/workflows/trivy-analysis.yml
=> fix workflows

AutomatedTests/Dockerfile, AutomatedTests/pom.xml, jag-ccd-application/Dockerfile, jag-ccd-application/pom.xml, jag-ccd-application/src/main/java/ca/bc/gov/open/ccd/controllers/CodeController.java, jag-ccd-application/src/main/java/ca/bc/gov/open/ccd/controllers/DocumentController.java, jag-ccd-application/src/main/java/ca/bc/gov/open/ccd/controllers/ReportController.java, pom.xml
=> update vulnerability and sprng boot to 3.4.4

.github/workflows/trivy-analysis.yml
=> update trivy scan

AutomatedTests/pom.xml, pom.xml
=> fix vulnerability
